runtime: python38
service: mlflow
instance_class: F2
entrypoint: mlflow ui --backend-store-uri $DB_URI --host 0.0.0.0 --port 8080 --default-artifact-root gs://$GCP_STORAGE_BUCKET

includes:
- secrets.yaml

vpc_access_connector:
  name: projects/$PROJECT_ID/locations/$REGION/connectors/$CONNECTOR_NAME
