runtime: python38
service: mlflow

entrypoint: mlflow server --backend-store-uri $DB_URI --host 0.0.0.0 --port 8080 --default-artifact-root gs://$GCP_STORAGE_BUCKET

includes:
- secrets.yaml

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

vpc_access_connector:
  name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
